baseURL: "https://www.marcogomiero.com"
title: Marco Gomiero
paginate: 12
theme: mg

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-69FZ1TLE7E

minify:
  disableXML: true
  minifyOutput: true

pygmentsstyle: "base16-snazzy"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

params:
  # Dark mode switcher
  mode: toggle
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Marco Gomiero
  description: "Software Engineer Â· Google Developer Expert for Android"
  keywords : [Marco Gomiero, Android, Flutter, Gomiero, Kotlin, RSS Parser, Kotlin Multiplatform]
  author: Marco Gomiero
  DateFormat: "2 January 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  assets:
    #disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  socialIcons:
    - name: github
      url: "https://github.com/prof18"
    - name: mastodon
      url: "https://androiddev.social/@marcogom"
    - name: bluesky
      url: "https://bsky.app/profile/marcogomiero.com"  
    - name: twitter
      url: "https://twitter.com/marcoGomier"
    - name: linkedin
      url: "https://linkedin.com/in/marco-gomiero"

  analytics:
    google:
      SiteVerificationTag: "7rDTNqn214SsZ9mmV8Ps5v2vqy8aXFWyoq08udChYCs"

menu:
  main:
    - identifier: posts
      name: Write
      url: /posts/
      weight: 1
    - identifier: talks
      name: Speak
      url: /talks/
      weight: 2
    - identifier: projects
      name: Build
      url: /projects/
      weight: 3
    - identifier: about
      name: About
      url: /about-me/
      weight: 4
